import { motion } from "framer-motion";

// 2. Defining Variants
const marqueeVariants = {
  animate: {
    x: [0, -1035],
    transition: {
      x: {
        repeat: Infinity,
        repeatType: "loop",
        duration: 30,
        ease: "linear",
      },
    },
  },
};

export default function SlidingText() {
    const words: string[] = [
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
        'Branding Design',
        'Art Direction',
        'Graphic Design',
        'Visual Strategies',
        'Motion Design',
    ];
    return (
    <div>
      <div className="marquee">
        <motion.div
          className="track"
          variants={marqueeVariants}
          animate="animate"
        >
          {words.map((_word:string, id:number) => { 
            return (
                <span key={`span-${_word}-${id}`}>{_word}</span>
            )
         })}
        </motion.div>
      </div>
    </div>
  );
};